#!/usr/bin/env bash

lolcat() {
  awk '
    BEGIN {
        freq = 0.1
        spread = 3.0
        pi = atan2(0,-1)
        offset = 0
    }

    function rainbow(f,s,  t, r,g,b) {
        t = f*s
        r = sin(t + 0) * 127 + 128
        g = sin(t + 2*pi/3) * 127 + 128
        b = sin(t + 4*pi/3) * 127 + 128
        return sprintf("%d;%d;%d", r,g,b)
    }
    {
        nchars = split($0, chars, "")
        for(i=1; i<=nchars; i++) {
            color = rainbow(freq, offset+i/spread)
            printf("\033[38;2;%sm%s%s", color, chars[i], "\033[39m")
        }
        offset += spread
        printf("\n")
    }' "$@"
}

s2cs() {
  typeset s=$(LANG=C;printf '%.2f' "$1")
  printf '%s' "${s/[.]/}"
}

now() {
  typeset t="${EPOCHREALTIME/,/.}"
  [ "$t" ] || read -r t _ 2>/dev/null </proc/uptime
  [ "$t" ] || t=$SECONDS
  s2cs "$t"
}

do_logo() {
  typeset text twidth nspaces spaces timeout=$(s2cs "$1") delay="$2"
  typeset -i off=$RANDOM i=10
  shift 2
  mapfile -t text                     # put logo in array
  trap 'tput cnorm' EXIT              # restore cursor at exit
  tput civis                          # hide cursor
  printf "%s\n" "${text[@]}" |lolcat freq=0.15 spread=2.0 offset=$off "$@"
  stime=$(now)
  end=$(($stime+$timeout))
  while [ $(now) -le $end ];do       # anim colors changing rainbow offset
    sleep $delay
    tput cuu ${#text[@]}              # cursor up nb logo lines
    printf "%s\n" "${text[@]}" |lolcat freq=0.15 spread=2.0 offset=$((off-i)) "$@"
    i=$((i+10))
  done
}

usage() {
  printf '\033]?7l'
  echo "usage: ${0##*/} [-t <tmoutsec>] [-s <sleepsec>] [-F] [figletopts] [<message>] [lolcatopts]

    -F            : Display <message> with all fonts in <fontdir>
    -t <tmoutsec> : animation duration (default 2.0)
    -s <sleepsec> : sleep between frales (default 0.1)
    <message>     : message to display (if not uses stdin w/o figlet)
    figletopts:
      -l|-r : left / right align (default center)
      -d <fontdir> : font directory
      -f <font> : font name
    lolcatopts:
      spread=<spread> : default 2.0
      freq=<freq>     : default 0.15
" |fold -w $width |do_logo 0.5 0.1
  printf '\033]?7h'
  exit 1
}

timeout=2.0
delay=0.1
allfonts=false
width=$(tput cols)
fontdir=$(figlet -I2 2>/dev/null)
figargs=()
while getopts ":t:s:d:f:lrFh" opt; do
  case "$opt" in
    t) timeout="$OPTARG";;
    s) delay="$OPTARG";;
    l|r) figargs+=("-$opt");;
    F) allfonts=true;;
    f|d) figargs+=(-"$opt" "$OPTARG");fontdir="$OPTARG";;
    h) usage;;
    :) echo "Option -$OPTARG requires an argument"; usage ;;
    \?) echo "Invalid option: -$OPTARG"; usage;;
  esac
done

shift $((OPTIND - 1))
text="$1"
shift
$allfonts && {
  shift
  cd "$fontdir"
  for i in *.?lf;do
    font=${i%.*}
    echo $font":"
    figlet -c -w $width"${figargs[@]}" -f "$i" "${text:-${font^} 123}" |do_logo $timeout $delay "$@"
  done
  exit
}
if [ "$text" ] ;then
  ! type figlet >/dev/null 2>&1 && do_logo $timeout $delay "$@" <<<"$text" && exit
  figlet -c -w $width "${figargs[@]}" "$text" |do_logo $timeout $delay "$@"
else
  do_logo $timeout $delay "$@"
fi
